backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

media_folder: static/img
public_folder: /img

collections:
  - name: "production"
    label: "Films"
    folder: "src/pages/production"
    create: true
    slug: "{{slug}}"
    required: false
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "production-post", required: false}
      - {label: "Title", name: "title", widget: "string", required: false}
      - {label: "Date de sortie", name: "date", widget: "datetime", hint: "Date réelle ou estimée. Seule l'année est affiché, mais l'ensemble de la date sert au trie.", required: false}
      - {label: "Réalisateur·trice", name: "director", widget: "string", required: false}
      - {label: "Featured Image", name: "featuredimage", widget: image, required: false}
      - {label: "Bande-annonce", name: "trailer", widget: "string", hint: "URL de la vidéo. Exemple : https://www.youtube.com/watch?v=9D0eyl7-XQA", required: false}
      - {label: "VOD", name: "vod", widget: "string", hint: "URL de la page de VOD.", required: false}
      - {label: "Introduction", name: "description", widget: "markdown", buttons: ["bold", "italic", "link"],editorComponents: [], required: false}
      - {label: "Body", name: "body", widget: "markdown", required: false}
      - {label: "Équipe", name: "team", widget: "markdown", required: false}
      - {label: "Sélections", name: "selection", widget: "markdown", required: false}
      - {label: "Production", name: "production", widget: "markdown", required: false}
      - {label: "Featured Post", name: "featuredpost", widget: "boolean", required: false}
      - {label: "Tags", name: "tags", widget: "list", hint: "'documentaire' ou 'fiction'", required: false}

  - name: "settings"
    label: "Réglages"
    files:
      - label: "Contact"
        name: contact
        file: src/settings/contact.json
        fields: 
          - {name: "address", label: "Adresse", widget: text, required: false}
          - {name: "phone", label: "Téléphone", widget: string, required: false}
          - {name: "email", label: "Courriel", widget: string, required: false}

  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    required: false
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Featured Post", name: "featuredpost", widget: "boolean"}
      - {label: "Featured Image", name: "featuredimage", widget: image}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}

  - name: "pages"
    label: "Pages"
    files:

      - file: "src/pages/production.md"
        label: "Page Production"
        name: "productionpage"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "production-page"}
          - {label: Title, name: title, widget: string}
          - {label: "Introduction", name: "description", widget: "markdown", buttons: ["bold", "italic", "link"], editorComponents: [], required: false}
          - {label: "Featured Image", name: "featuredimage", widget: image, required: false}

      - file: "src/pages/index.md"
        label: "Landing Page"
        name: "index"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "index-page"}
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Heading, name: heading, widget: string}
          - {label: Subheading, name: subheading, widget: string}
          - {label: Mainpitch, name: mainpitch, widget: object, fields: [{label: Title, name: title, widget: string}, {label: Description, name: description, widget: text}]}
          - {label: Description, name: description, widget: string}
          - {label: Intro, name: intro, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Blurbs, name: blurbs, widget: list, fields: [{label: Image, name: image, widget: image}, {label: Text, name: text, widget: text}]}]}
          - {label: Main, name: main, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Image1, name: image1, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image2, name: image2, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image3, name: image3, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}]}

      - file: "src/pages/about/index.md"
        label: "About"
        name: "about"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/products/index.md"
        label: "Products Page"
        name: "products"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "product-page"}
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Heading, name: heading, widget: string}
          - {label: Description, name: description, widget: string}
          - {label: Intro, name: intro, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Blurbs, name: blurbs, widget: list, fields: [{label: Image, name: image, widget: image}, {label: Text, name: text, widget: text}]}]}
          - {label: Main, name: main, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Image1, name: image1, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image2, name: image2, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image3, name: image3, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}]}
          - {label: Testimonials, name: testimonials, widget: list, fields: [{label: Quote, name: quote, widget: string}, {label: Author, name: author, widget: string}]}
          - {label: Full_image, name: full_image, widget: image}
          - {label: Pricing, name: pricing, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: string}, {label: Plans, name: plans, widget: list, fields: [{label: Plan, name: plan, widget: string}, {label: Price, name: price, widget: string}, {label: Description, name: description, widget: string}, {label: Items, name: items, widget: list}]}]}